name: Nahvino
description: Nahvino.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  get: ^4.6.5
  get_storage:
  intl: ^0.17.0
  flutter_html:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  #OTP
  pin_code_fields: ^7.4.0
  #timer_button: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  cupertino_icons: ^1.0.2
  lottie: ^1.1.0
  webview_flutter: ^2.0.9
  # Google Icon
  font_awesome_flutter: ^9.2.0
  # State Management
  http: ^0.13.4
  shared_preferences: ^2.0.13
  persian_datetime_picker: ^2.4.0
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.12
  accordion: ^2.2.3
  image_picker: ^0.8.4+11
  connectivity: ^3.0.6
  # Chat
  signalr_core: ^1.1.1
  socket_io_client: ^1.0.2
  flutter_emoji: ^2.4.0
  emoji_picker_flutter: ^1.1.2
  flutter_local_notifications: ^9.4.1
  #flutter_background_service: ^2.0.0
  device_info_plus: ^3.2.3
  chat_bubbles: ^1.2.0
  scrollable_positioned_list:
  flutter_chat_bubble: ^2.0.0
  share_plus: ^4.0.4
  #notifications:
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.4
  overlay_support: ^2.0.1
  pinput: ^2.2.7
  #cacheimage
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  percent_indicator: ^4.0.0
  otp_timer_button: ^1.1.0
  #phonenumber
  mask_text_input_formatter: ^2.3.0
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.5
  path_provider: ^2.0.11
  double_back_to_close: ^2.0.0
  #right button
  swipeable_tile: ^2.0.0+1
  #new virtion
  once: ^1.4.1
  #downloader
  flutter_downloader: ^1.8.1
  #permission
  permission_handler: ^9.2.0
  #Tabbar
  #menu
  pull_down_button: ^0.1.0-beta.6
  focused_menu: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.2

flutter:
  fonts:
    - family: Vazirmatn_Black
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Black.ttf

    - family: Vazirmatn_Bold
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Bold.ttf

    - family: Vazirmatn_ExtraBold
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-ExtraBold.ttf

    - family: Vazirmatn_ExtraLight
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-ExtraLight.ttf

    - family: Vazirmatn_Light
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Light.ttf

    - family: Vazirmatn_Medium
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Medium.ttf

    - family: Vazirmatn_Regular
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Regular.ttf

    - family: Vazirmatn_SemiBold
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-SemiBold.ttf

    - family: Vazirmatn_Thin
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Thin.ttf

  assets:
    - assets/splash/animtiopsh.json
    - assets/lang/fa.json
    - assets/lang/en.json
    - assets/images/
    - assets/images/icon/
    - assets/images/login/
    - assets/images/ram/
    - assets/images/sinupbak.png
    - assets/anim/
    - assets/anim/loading/
    - assets/anim/phonix/
    - assets/anim/login/
    - assets/anim/user/
    - assets/anim/chat/
    - assets/anim/viewprofile/
    - assets/images/home/

  uses-material-design: true
