name: nahvino
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  get: ^4.1.4
  intl: ^0.17.0
  flutter_html:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  #OTP
  sms_autofill: ^2.2.0
  timer_button: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  cupertino_icons: ^1.0.2
  lottie: ^1.1.0
  webview_flutter: ^2.0.9
  # Google Icon
  font_awesome_flutter: ^9.2.0
  # State Management
  provider: ^6.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  persian_datetime_picker: ^2.4.0
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.12
  accordion: ^2.2.3
  image_picker: ^0.8.4+11
  connectivity: ^3.0.6
  # Chat
  signalr_core: ^1.1.1
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.2

flutter:
  fonts:
    - family: vazirlight
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Light.ttf
    - family: byekan
      fonts:
        - asset: fonts/byekan.ttf

  assets:
   - assets/splash/animtiopsh.json
   - assets/lang/fa.json
   - assets/lang/en.json 
   - assets/images/
   - assets/images/login/
   - assets/images/sinupbak.png
   - assets/anim/data.json
   - assets/images/home/

  uses-material-design: true
