name: Nahvino
description: Nahvino.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.3+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  get: ^4.1.4
  intl: ^0.17.0
  flutter_html:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  #OTP
  pin_code_fields: ^7.4.0
  timer_button: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  cupertino_icons: ^1.0.2
  lottie: ^1.1.0
  webview_flutter: ^2.0.9
  # Google Icon
  font_awesome_flutter: ^9.2.0
  # State Management
  provider: ^6.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  persian_datetime_picker: ^2.4.0
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.12
  accordion: ^2.2.3
  image_picker: ^0.8.4+11
  connectivity: ^3.0.6
  # Chat
  signalr_core: ^1.1.1
  socket_io_client: ^1.0.2
  flutter_emoji: ^2.4.0
  emoji_picker_flutter: ^1.1.2
  flutter_local_notifications: ^9.4.1
  flutter_background_service: ^2.0.0
  device_info_plus: ^3.2.3
  chat_bubbles: ^1.2.0
  flutter_chat_bubble: ^2.0.0
  share_plus: ^4.0.4
  firebase_core: any
  firebase_messaging: ^10.0.0
  new_version: ^0.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.2

flutter:
  fonts:
    - family: Vazirmatn_Black
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Black.ttf

    - family: Vazirmatn_Bold
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Bold.ttf

    - family: Vazirmatn_ExtraBold
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-ExtraBold.ttf

    - family: Vazirmatn_ExtraLight
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-ExtraLight.ttf

    - family: Vazirmatn_Light
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Light.ttf

    - family: Vazirmatn_Medium
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Medium.ttf

    - family: Vazirmatn_Regular
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Regular.ttf

    - family: Vazirmatn_SemiBold
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-SemiBold.ttf

    - family: Vazirmatn_Thin
      fonts:
        - asset: fonts/Vazirmatn-UI-FD-NL-Thin.ttf

  assets:
    - assets/splash/animtiopsh.json
    - assets/lang/fa.json
    - assets/lang/en.json
    - assets/images/
    - assets/images/login/
    - assets/images/ram/
    - assets/images/sinupbak.png
    - assets/anim/data.json
    - assets/anim/
    - assets/anim/login/
    - assets/anim/user/
    - assets/anim/viewprofile/
    - assets/images/home/

  uses-material-design: true
